import { Inter } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/redux/provider';
import AuthInitializer from '@/redux/AuthInitializer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'pzkosz NBA',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthInitializer>{children}</AuthInitializer>
        </ReduxProvider>
      </body>
    </html>
  );
}
