export const ACTION_TYPES_MATCH = {
  FETCH_TEAMS: 'FETCH_TEAMS',
  SET_DATE: 'SET_DATE',
  SELECT_TEAM: 'SELECT_TEAM',
  UPDATE_PLAYERS: 'UPDATE_PLAYERS',
  UPDATE_OPPONENTS: 'UPDATE_OPPONENTS'
};

export const ACTION_TYPES_LOGIN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CHANGE_TEAM: 'CHANGE_TEAM'
};
