import { Inter } from 'next/font/google';
import '.app//globals.css';
import { ReduxProvider } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'pzkosz NBA',
  description: 'Generated by create next app'
};

export default function PagesLayout({ children }) {
  return <ReduxProvider>{children}</ReduxProvider>;
}
